apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: fbc-component
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: fbc-test
    app.kubernetes.io/part-of: fbc-app
  name: fbc-component
  namespace: managed
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/instance: fbc-component
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app.kubernetes.io/instance: fbc-component
    spec:
      containers:
      - image: quay.io/lmendes/user-workload@sha256:be1edf1ff7ee5c819ed9e456e7f6ebb1461abb7727ff52c7daad3fdbc5cf258b
        imagePullPolicy: Always
        name: container-image
        resources: {}
status: {}
