apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: fbc-component
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: fbc-test
    app.kubernetes.io/part-of: fbc-app
  name: fbc-component
  namespace: managed
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/instance: fbc-component
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app.kubernetes.io/instance: fbc-component
    spec:
      containers:
      - image: quay.io/lmendes/user-workload@sha256:9186a8a7857d27f9f4a36f9a935a105b634d846c49ea95d26cb524975f70412b
        imagePullPolicy: Always
        name: container-image
        resources: {}
status: {}
