apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: fbc-component
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: fbc-test
    app.kubernetes.io/part-of: fbc-app
  name: fbc-component
  namespace: managed
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/instance: fbc-component
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app.kubernetes.io/instance: fbc-component
    spec:
      containers:
      - image: quay.io/lmendes/user-workload@sha256:67db0a50ebef10c1c163e87b08345898a7d6a16d112b589443745aaf7dd61f0f
        imagePullPolicy: Always
        name: container-image
        resources: {}
status: {}
