apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: fbc-component
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: fbc-test
    app.kubernetes.io/part-of: fbc-app
  name: fbc-component
  namespace: managed
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/instance: fbc-component
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app.kubernetes.io/instance: fbc-component
    spec:
      containers:
      - image: quay.io/lmendes/user-workload@sha256:96f43a7679936aa3cccd644a66c052409e4fcef4f470bfb4bd86965e64aa5fb5
        imagePullPolicy: Always
        name: container-image
        resources: {}
status: {}
